# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RwiOlAv7gpIDynu3Qwr8eAijiP8Y-uN
"""

import pandas as pd
import seaborn as sns

dt=pd.read_csv("/Mall_Customers.csv")

dt.info()

for i in dt.columns:
   if dt[i].dtype =='object':
     dt[i]=dt[i].astype('category').cat.codes

dt.info()

x=dt.iloc[:,3:]
x.head()

from sklearn.cluster import KMeans

wcss = []
for i in range(1,11):
  kMeans=KMeans(n_clusters=i,init="k-means++",random_state=42)
  kMeans.fit(x)
  wcss.append(kMeans.inertia_)

import matplotlib.pyplot as plt
plt.plot(range(1,11),wcss)
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

kMeans = KMeans(n_clusters=5,init="k-means++",random_state=42)
y_kmeans = kMeans.fit_predict(x)

labels = kMeans.labels_
dt['cluster']=labels

plt.scatter(dt['Annual Income (k$)'],dt['Spending Score (1-100)'], c=dt['cluster'])
plt.title('Mall Customer segmentation')
plt.xlabel('Age')
plt.ylabel('Spending Score')
plt.show()