# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1ahwYN0vryHd8d78B5xeHO_-_OEsGG6
"""

import pandas as pd
import seaborn as sns

"""q

for i in dt.columns:
   if dt[i].type =='object':
     dt[i]=dt[i].astype('category').cat.codes
"""

dt=pd.read_csv('/WA_Fn-UseC_-Telco-Customer-Churn.csv')

dt.info()

from google.colab import drive
drive.mount('/content/drive')

for i in dt.columns:
   if dt[i].dtype == 'object':
    dt[i] = dt[i].astype('category').cat.codes

dt.info()

dt.drop(["customerID"], axis=1, inplace=True)

dt=dt.drop(["gender", "Dependents","PhoneService","MultipleLines", "InternetService"],axis = 1)

dt = dt.drop(["StreamingTV","StreamingMovies","TotalCharges"], axis=1, errors='ignore')

x = dt.drop(["Churn"], axis=1)
y=  dt["Churn"]

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2)

sns.pairplot(data = dt, hue= 'Churn')

from sklearn.tree import DecisionTreeClassifier
d = DecisionTreeClassifier()

d.fit(xtrain,ytrain)

ypred = d.predict(xtest)

from sklearn.metrics import accuracy_score

accuracy_score(ytest,ypred)