# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Hup3cRP6HZOAUtR1yE5gzueGG-5ty3z
"""

!pip install transformers

from transformers import pipeline

a=pipeline("sentiment-analysis")

text = input("Enter the text:")
print(a(text))

gen = pipeline('text-generation')

text = input("Enter the text: ")
t = gen(text,max_length = 200)

print(t[0].get('generated_text'))

n=pipeline('ner')

text = input("Enter a text:")
result = n(text)
result

qa = pipeline('question-answer')

c = '''Bity bought some butter, but the butter was bitter butter.
SO, Bitty bought some bettter butter, to make bitter butter better'''

q = "What does Bitty bought?"

result = qa({'question': q, 'context': c})
print(result)

s =  pipeline('summarization')

t = ''' Computer vision is a field of artificial intelligence (AI) that focuses
on enabling computers to "see" and interpret the visual world, just like humans
do. It involves using algorithms and models to extract information from images
and videos, allowing computers to identify objects, detect patterns, and make
decisions based on what they see.'''

result = s(t)
print(result[0].get('summary_text'))

u = pipeline('fill-mask')

result = u("I'm teaching <mask> the board")
result

